# Generated by Django 4.2.19 on 2025-03-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=20, unique=True, verbose_name="이메일")),
                ("nickname", models.CharField(max_length=20, verbose_name="닉네임")),
                ("name", models.CharField(max_length=10, verbose_name="이름")),
                ("phone_number", models.CharField(max_length=20, unique=True, verbose_name="전화번호")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프 여부")),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자 여부")),
                ("is_active", models.BooleanField(default=False, verbose_name="활성 여부")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_number", models.CharField(max_length=30, unique=True, verbose_name="계좌번호")),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("000", "알수없음"),
                            ("001", "한국은행"),
                            ("002", "산업은행"),
                            ("003", "기업은행"),
                            ("004", "국민은행"),
                            ("005", "외환은행"),
                            ("007", "수협중앙회"),
                            ("008", "수출입은행"),
                            ("011", "농협은행"),
                            ("012", "지역농.축협"),
                            ("020", "우리은행"),
                            ("023", "SC은행"),
                            ("027", "한국씨티은행"),
                            ("031", "대구은행"),
                            ("032", "부산은행"),
                            ("034", "광주은행"),
                            ("035", "제주은행"),
                            ("037", "전북은행"),
                            ("039", "경남은행"),
                            ("045", "새마을금고중앙회"),
                            ("048", "신협중앙회"),
                            ("050", "상호저축은행"),
                            ("051", "중국은행"),
                            ("052", "모건스탠리은행"),
                            ("054", "HSBC은행"),
                            ("055", "도이치은행"),
                            ("056", "알비에스피엘씨은행"),
                            ("057", "제이피모간체이스은행"),
                            ("058", "미즈호은행"),
                            ("059", "미쓰비시도쿄UFJ은행"),
                            ("060", "BOA은행"),
                            ("061", "비엔피파리바은행"),
                            ("062", "중국공상은행"),
                            ("063", "중국은행"),
                            ("064", "산림조합중앙회"),
                            ("065", "대화은행"),
                            ("066", "교통은행"),
                            ("071", "우체국"),
                            ("076", "신용보증기금"),
                            ("077", "기술보증기금"),
                            ("081", "KEB하나은행"),
                            ("088", "신한은행"),
                            ("089", "케이뱅크"),
                            ("090", "카카오뱅크"),
                            ("092", "토스뱅크"),
                            ("093", "한국주택금융공사"),
                            ("094", "서울보증보험"),
                            ("095", "경찰청"),
                            ("096", "한국전자금융(주)"),
                            ("099", "금융결제원"),
                            ("102", "대신저축은행"),
                            ("103", "에스비아이저축은행"),
                            ("104", "에이치케이저축은행"),
                            ("105", "웰컴저축은행"),
                            ("106", "신한저축은행"),
                            ("209", "유안타증권"),
                            ("218", "현대증권"),
                            ("221", "골든브릿지투자증권"),
                            ("222", "한양증권"),
                            ("223", "리딩투자증권"),
                            ("224", "BNK투자증권"),
                            ("225", "IBK투자증권"),
                            ("226", "KB투자증권"),
                            ("227", "KTB투자증권"),
                            ("230", "미래에셋증권"),
                            ("238", "대우증권"),
                            ("240", "삼성증권"),
                            ("243", "한국투자증권"),
                            ("261", "교보증권"),
                            ("262", "하이투자증권"),
                            ("263", "HMC투자증권"),
                            ("264", "키움증권"),
                            ("265", "이베스트투자증권"),
                            ("266", "SK증권"),
                            ("267", "대신증권"),
                            ("269", "한화투자증권"),
                            ("270", "하나대투증권"),
                            ("278", "신한금융투자"),
                            ("279", "DB금융투자"),
                            ("280", "유진투자증권"),
                            ("287", "메리츠종합금융증권"),
                            ("289", "NH투자증권"),
                            ("290", "부국증권"),
                            ("291", "신영증권"),
                            ("292", "엘아이지투자증권"),
                            ("293", "한국증권금융"),
                            ("294", "펀드온라인코리아"),
                            ("295", "우리종합금융"),
                            ("296", "삼성선물"),
                            ("297", "외환선물"),
                            ("298", "현대선물"),
                        ],
                        max_length=20,
                        verbose_name="은행 코드",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("입출금", "입출금"),
                            ("적금", "적금"),
                            ("대출", "대출"),
                            ("연금", "연금"),
                            ("신탁", "신탁"),
                            ("외화", "외화"),
                            ("퇴직연금", "퇴직연금"),
                            ("주식", "주식"),
                        ],
                        max_length=20,
                        verbose_name="계좌 종류",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="잔액")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저 정보",
                    ),
                ),
            ],
            options={
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌 목록",
            },
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_amount", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="거래 금액")),
                ("after_balance", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="잔액")),
                ("transaction_detail", models.CharField(max_length=30, verbose_name="계좌 인자 내역")),
                (
                    "deposit_withdrawal_type",
                    models.CharField(
                        choices=[("입금", "입금"), ("출금", "출금")], max_length=10, verbose_name="입출금 타입"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ATM", "ATM 거래"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTOMATIC_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                            ("INTEREST", "이자"),
                        ],
                        max_length=20,
                        verbose_name="거래 타입",
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True, verbose_name="거래 일시")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.account",
                        verbose_name="계좌 정보",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래 내역",
                "verbose_name_plural": "거래 내역 목록",
            },
        ),
        migrations.CreateModel(
            name="notifications",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(verbose_name="메세지 내용")),
                ("is_read", models.BooleanField(default=False, verbose_name="읽음 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="알림 수신 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림 목록",
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "target",
                    models.CharField(
                        choices=[("수입", "수입"), ("지출", "지출")], max_length=10, verbose_name="분석 대상"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("DAILY", "일간"), ("WEEKLY", "주간"), ("MONTHLY", "월간"), ("YEARLY", "연간")],
                        max_length=10,
                        verbose_name="분석 기간",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작 날짜")),
                ("end_date", models.DateField(verbose_name="종료 날짜")),
                ("description", models.TextField(blank=True, null=True, verbose_name="설명")),
                (
                    "result_image",
                    models.ImageField(blank=True, null=True, upload_to="analysis_images/", verbose_name="결과 이미지"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="분석 요청 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "분석",
                "verbose_name_plural": "분석 목록",
            },
        ),
    ]
